---
- hosts: proxy
  become: true
  roles:
    - geerlingguy.haproxy
  vars:
    haproxy_backend_servers:
      - name: rhel2
        address: 192.168.199.130
      - name: rhel3
        address: 192.168.199.131
    haproxy_backend_balance_method: 'roundrobin'
    haproxy_frontend_port: 80
  tasks:
    - name: Configure firewall to allow traffic
      firewalld:
        service: http
        state: enabled
        permanent: yes
      notify: reload firewalld

  handlers:
    - name: reload firewalld config
      service:
        name: firewalld
        state: reloaded
      listen: reload firewalld
