---
- hosts: all
  become: true
  vars_files:
    - vars/user_list.yaml
    - secret.yml
  tasks:
    - name: Create users starting with ID 1
      user:
        name: "{{ item.username }}"
        shell: /bin/bash
        password: "{{ user_password | password_hash('sha512') }}"
      when: '"web" in group_names and item.uid < 2000'
      with_items: "{{ users }}"

    - name: Create users starting with ID 1
      user:
        name: "{{ item.username }}"
        shell: /bin/bash
        password: "{{ user_password | password_hash('sha512') }}"
      when: '"db" in group_names and item.uid > 2000'
      with_items: "{{ users }}"
